version: "3"
services:
  postgres:
    container_name: twichat_postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - internal_network
    command: -p ${POSTGRES_PORT}

  web:
    container_name: twichat_web
    image: ghcr.io/iamtakagi/twichat_web:latest
    environment:
      TZ: Asia/Tokyo
      PORT: 3500
    networks:
      - external_network
    depends_on:
      - backend

  backend:
    container_name: twichat_backend
    image: ghcr.io/iamtakagi/twichat_backend:latest
    volumes:
      - ./backend/log/gunicorn:/app/log/gunicorn
    env_file:
      - .env
    command: >
      /bin/bash -c " python manage.py migrate && gunicorn -c /app/gunicorn.py twichat.wsgi"
    networks:
      - internal_network
      - external_network
    depends_on:
      - postgres

networks:
  external_network:
    external: true
  internal_network:
    internal: true
