version: "3"
services:

  web:
    container_name: renchon_chat
    image: ghcr.io/iamtakagi/renchon_chat:latest
    environment:
      TZ: Asia/Tokyo
      PORT: 3700
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true