version: '3'

services:
  app:
    container_name: anime-title-gacha
    image: ghcr.io/iamtakagi/anime-title-gacha:latest
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true