version: '3'

services:
  app:
    container_name: youtube-web-player
    image: ghcr.io/iamtakagi/youtube-web-player:latest
    environment:
      - TZ=Asia/Tokyo
      - PORT=4300
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true