version: '3'

services:
  app:
    container_name: renchon
    image: ghcr.io/iamtakagi/renchon:latest
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - external_network

networks:
  external_network:
    external: true