version: '3'

services:
  bot:
    container_name: renchon_bot
    image: ghcr.io/renchon-iamtakagi-net/bot:latest
    volumes:
      - ./data:/app/data
    env_file:
      - bot.env
    restart: unless-stopped
    networks:
      - proxy_network
  
  web:
    container_name: renchon_web
    image: ghcr.io/renchon-iamtakagi-net/web:latest
    env_file:
      - web.env
    networks:
      - proxy_network
    restart: unless-stopped

networks:
  proxy_network:
    external: true