version: '3'

services:
  bot:
    container_name: renchon_bot
    image: ghcr.io/renchon-chat/bot:latest
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy_network
  
  web:
    container_name: renchon_web
    image: ghcr.io/renchon-chat/web:latest
    environment:
      TZ: Asia/Tokyo
      PORT: 3700
    networks:
      - proxy_network
    restart: unless-stopped

networks:
  proxy_network:
    external: true