version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - internal_network
    env_file:
      - .env

  wordpress:
    depends_on:
      - mysql
    image: wordpress:php7.3-fpm
    volumes:
      - ./public:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 9000:9000
    restart: always
    networks:
      - internal_network
      - external_network
    env_file:
      - .env

networks:
    internal_network:
      internal: true
    external_network:
      external: true