version: '3.8'

services:
  app:
    container_name: images
    image: ghcr.io/iamtakagi/images:latest
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - PORT=2270
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true