version: '3'

services:
  app:
    container_name: shadowban-alerts
    image: ghcr.io/iamtakagi/shadowban-alerts:latest
    volumes:
      - './crontab:/app/crontab'
      - './ShadowbanAlerts.json:/app/ShadowbanAlerts.json'
    env_file:
      - .env