version: '3'

services:
  app:
    container_name: ai
    image: ghcr.io/iamtakagi/takagi.ai
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - external_network
    restart: unless-stopped

networks:
  external_network:
    external: true
